Feature/product information page (#115)
* Modified ProductDisplay and Products page

- Have structured as it is in the design.
- Little product displays at the bottom has been appropriately styled.
- Big product display is still in the works (styling still not finished and carousel not implemented yet).

* Major Change Carousel.tsx

Did major plastic surgery. Carousel now has children nodes inside it, not predetermined image-focused ones made in the file itself. It is now also scroll-controlled rather than by buttons.

Tested for functionality (improved).

* Basic Layout

Change implemented on the (singular) product page:
- Images scrolling vertically (rather than the products scrolling horizontally carousel that I previously thought).
-> Added a 'additionalImages' type in products.ts
- Description box made.

Other changes:
- Fixed up the carousel a little bit (even though it's not needed for this one anymore).

* Final Changes to Products Page + Buttons

- Scrolling additionalImages (but also when in phone-sized screen).
- Dynamic/flexible layout.
- Matches the updated design.
- Buttons added.

Need to do:
- Horizontal carousel for the additionalImages in phone screen size.
- Connect incrementor with addToCart button.

* Buttons Update

The Incrementor is now connected to the AddToCart through the ProductDisplayBig file.

* Carousel for Mobile Version

+ deleted the number in the 'add to bag' button text.
+ got rid of isImageCarousel required boolean in Carousel.tsx & fixed it up a little (so that the image is contained inside, basically).

Made the image a carousel in a phone screen (it would be annoying to have to scroll through all the product's images to get through otherwise).

* Scrolling Image Escaped

Contained them again.
- Missed adding a height constraint into the div className.

* Amount Cap

Last minute (forgotten) addition: the incrementor has a max cap of 50 unless specifically stated.

* Container Centered

.

* Carousel Functionality

- Dots changes when scrolling as well (it wasn't in a previous iteration).
- Added visibility that indicates the dots can, in fact, be pressed.

* Fixing Errors

Added key for both productDisplay and productDisplayBig.

* key type

Did not need to explicitly state a key prop.

* payloads.types Empty

Temporary (?) fix: copy pasted the code so it doesn't disappear again.

* key Error

Error: Each child in a list should have a unique "key" prop.

Deleted the key in the ProductsDisplayBig of the page.tsx. Found that the error originated from the picture box - top part.

(Also in previous commit: changed <a> to <Link> in Products Display)

+ payload-types re-generated.

* fix: aligned versions of lexical for consistency and error fix

* fix/pnpm build errors

* fix:updated pnpm-lock

* fixing build errors AHHH

---------

Co-authored-by: Dahyun Ha <162376263+dha524@users.noreply.github.com>
Co-authored-by: Shazeel Ali <75409190+ShazeelAli@users.noreply.github.com>